---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: wayscreen
# description will be included in the image's metadata
description: A Wayland based multi screen media consumption distro

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
    install:
      packages:
        - hyprland
        - hyprland-devel
        - xdg-desktop-portal-hyprland
        - hyprland-contrib
        - hyprland-plugins
        - hyprland-qtutils
        - hyprpaper
        - hyprpolkitagent
        - sway
        - sddm
        - sddm-themes
        - mpv
        - mpv-libs
        - python3-pip
        - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        # X11 until Deskflow client works
        - xorg-x11-server-Xorg
        - xorg-x11-server-Xvfb
        - xorg-x11-server-common
        - xorg-x11-server-devel
        - linux-firmware
        - amd-gpu-firmware
        - xorg-x11-drv-amdgpu
        - amdsmi
        - i3
        - rofi
        - feh
        - xdotool
        - xev
        - xrandr
        - arandr
        - xset
        - xsetroot
        - xwininfo
        - numlockx
        - wmctrl
        - picom
        - unclutter-xfixes
        - dbus-x11
        - python3-tkinter
        - xbindkeys
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: false
      - scope: user
        install:
          - org.deskflow.deskflow
          - org.mozilla.firefox
          - org.remmina.Remmina
          - org.videolan.VLC

  - type: script
    scripts:
      - build.sh

  - type: systemd
    system:
      enabled:
        - sshd.service
        - serial-getty@ttyS0.service
        - onboot.service
        - var-mnt-sscd.mount
      disabled:
        - flatpak-system-update.timer
        - system-flatpak-setup.timer
        - rpm-ostree-countme.timer
    user:
      disabled:
        - flatpak-user-update.timer
        - user-flatpak-setup.timer

  - type: signing
